#!/usr/bin/env python3
"""Generate the application's icon set.

The 2014 build shipped icons lifted from the Eclipse Platform debug UI and from an unidentified
Creative Commons set. Rather than guess at the provenance of each file for a NOTICE, the icons are
drawn here: everything the program ships is generated by this script and carries the project's own
licence.

Run from the repository root:

    python tools/generate_icons.py

Requires Pillow.
"""

from __future__ import annotations

import pathlib

from PIL import Image, ImageDraw

RES = pathlib.Path(__file__).resolve().parent.parent / "src" / "main" / "resources" / "pixelbot"

# Supersampling factor: everything is drawn large and reduced, so 16px glyphs stay smooth.
S = 16

INK = (0x2B, 0x33, 0x42, 255)      # outlines and neutral glyphs
BLUE = (0x5B, 0x7F, 0xA8, 255)     # navigation / passive actions
AMBER = (0xE8, 0xB3, 0x4A, 255)    # the accent from the application icon
GREEN = (0x5F, 0xA8, 0x6B, 255)    # go
RED = (0xD9, 0x57, 0x57, 255)      # stop / destructive
GREY = (0x8A, 0x93, 0xA0, 255)     # dismiss

BACKGROUND = (0, 0, 0, 0)


class Canvas:
    """A 16x16 icon drawn at S times the size and reduced on save."""

    def __init__(self, width: int = 16, height: int = 16):
        self.width = width
        self.height = height
        self.image = Image.new("RGBA", (width * S, height * S), BACKGROUND)
        self.draw = ImageDraw.Draw(self.image)

    def _s(self, points):
        return [(x * S, y * S) for x, y in points]

    def polygon(self, points, fill):
        self.draw.polygon(self._s(points), fill=fill)

    def rect(self, x0, y0, x1, y1, fill):
        self.draw.rectangle([x0 * S, y0 * S, x1 * S - 1, y1 * S - 1], fill=fill)

    def rounded(self, x0, y0, x1, y1, radius, fill=None, outline=None, width=1):
        self.draw.rounded_rectangle(
            [x0 * S, y0 * S, x1 * S - 1, y1 * S - 1],
            radius=radius * S,
            fill=fill,
            outline=outline,
            width=int(width * S),
        )

    def ellipse(self, x0, y0, x1, y1, fill=None, outline=None, width=1):
        self.draw.ellipse(
            [x0 * S, y0 * S, x1 * S - 1, y1 * S - 1],
            fill=fill,
            outline=outline,
            width=int(width * S),
        )

    def arc(self, x0, y0, x1, y1, start, end, fill, width):
        self.draw.arc(
            [x0 * S, y0 * S, x1 * S - 1, y1 * S - 1],
            start=start,
            end=end,
            fill=fill,
            width=int(width * S),
        )

    def line(self, points, fill, width):
        self.draw.line(self._s(points), fill=fill, width=int(width * S), joint="curve")

    def save(self, relative: str) -> None:
        path = RES / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        self.image.resize((self.width, self.height), Image.LANCZOS).save(path)
        print("wrote", path.relative_to(RES.parent))


def play_triangle(c: Canvas, x: float, colour) -> None:
    c.polygon([(x, 3), (x, 13), (x + 7.5, 8)], colour)


def arrow_head(c: Canvas, tip, direction, size, colour) -> None:
    """A solid triangular head at `tip` pointing 'up', 'down', 'left' or 'right'."""
    x, y = tip
    h = size
    if direction == "down":
        c.polygon([(x - h, y - h), (x + h, y - h), (x, y)], colour)
    elif direction == "up":
        c.polygon([(x - h, y + h), (x + h, y + h), (x, y)], colour)
    elif direction == "right":
        c.polygon([(x - h, y - h), (x - h, y + h), (x, y)], colour)
    else:
        c.polygon([(x + h, y - h), (x + h, y + h), (x, y)], colour)


def run_icon():
    c = Canvas()
    play_triangle(c, 4, GREEN)
    return c, "resources/run.png"


def debug_icon():
    c = Canvas()
    play_triangle(c, 3, GREEN)
    c.ellipse(9.5, 9.5, 15.5, 15.5, fill=RED)
    return c, "resources/debug.png"


def resume_icon():
    c = Canvas()
    c.rect(3, 3, 5, 13, BLUE)
    c.polygon([(6.5, 3), (6.5, 13), (13.5, 8)], BLUE)
    return c, "resources/resume.png"


def suspend_icon():
    c = Canvas()
    c.rect(4, 3, 7, 13, BLUE)
    c.rect(9, 3, 12, 13, BLUE)
    return c, "resources/suspend.png"


def terminate_icon():
    c = Canvas()
    c.rounded(3.5, 3.5, 12.5, 12.5, 1, fill=RED)
    return c, "resources/terminate.png"


def step_into_icon():
    c = Canvas()
    c.line([(8, 2), (8, 9)], BLUE, 2)
    arrow_head(c, (8, 12.5), "down", 3, BLUE)
    c.rect(4, 13.5, 12, 15, INK)
    return c, "resources/stepinto.png"


def step_over_icon():
    c = Canvas()
    c.arc(3, 4, 13, 14, start=180, end=360, fill=BLUE, width=2)
    arrow_head(c, (12.8, 9.5), "down", 2.8, BLUE)
    c.ellipse(6, 11.5, 10, 15.5, fill=INK)
    return c, "resources/stepover.png"


def step_return_icon():
    c = Canvas()
    c.line([(8, 13.5), (8, 6.5)], BLUE, 2)
    arrow_head(c, (8, 3), "up", 3, BLUE)
    c.rect(4, 14, 12, 15.5, INK)
    return c, "resources/stepreturn.png"


def breakpoint_icon():
    c = Canvas()
    c.ellipse(3, 3, 13, 13, fill=(0x3C, 0x6E, 0xA8, 255))
    return c, "components/editor/resources/brkp_obj.png"


def close_icon():
    c = Canvas()
    c.line([(4.5, 4.5), (11.5, 11.5)], GREY, 1.8)
    c.line([(11.5, 4.5), (4.5, 11.5)], GREY, 1.8)
    return c, "resources/close-icon.png"


def add_icon():
    c = Canvas()
    c.rect(7, 3, 9, 13, GREEN)
    c.rect(3, 7, 13, 9, GREEN)
    return c, "resources/elements/add.png"


def delete_icon():
    c = Canvas()
    c.line([(4, 4), (12, 12)], RED, 2.2)
    c.line([(12, 4), (4, 12)], RED, 2.2)
    return c, "resources/elements/delete.png"


def replace_icon():
    c = Canvas()
    c.line([(3.5, 5.5), (11, 5.5)], AMBER, 1.8)
    arrow_head(c, (13, 5.5), "right", 2.6, AMBER)
    c.line([(12.5, 10.5), (5, 10.5)], AMBER, 1.8)
    arrow_head(c, (3, 10.5), "left", 2.6, AMBER)
    return c, "resources/elements/replace.png"


def save_icon():
    c = Canvas()
    c.rounded(2.5, 2.5, 13.5, 13.5, 1, fill=BLUE)
    c.rect(5.5, 2.5, 10.5, 6.5, (0xE6, 0xEC, 0xF2, 255))
    c.rect(4.5, 8.5, 11.5, 13.5, (0xE6, 0xEC, 0xF2, 255))
    return c, "resources/elements/save.png"


def export_icon():
    c = Canvas()
    c.rounded(2.5, 4.5, 10.5, 13.5, 1, outline=BLUE, width=1.4)
    c.line([(7, 9), (12, 9)], BLUE, 1.8)
    arrow_head(c, (14.5, 9), "right", 2.8, BLUE)
    return c, "resources/elements/export.png"


def grab_icon():
    c = Canvas()
    for x0, y0, x1, y1 in ((2, 2, 6, 3), (2, 2, 3, 6), (10, 2, 14, 3), (13, 2, 14, 6),
                           (2, 13, 6, 14), (2, 10, 3, 14), (10, 13, 14, 14), (13, 10, 14, 14)):
        c.rect(x0, y0, x1, y1, AMBER)
    c.rect(6.5, 6.5, 9.5, 9.5, AMBER)
    return c, "resources/elements/grab.png"


def test_icon():
    c = Canvas()
    c.ellipse(2.5, 2.5, 11.5, 11.5, outline=BLUE, width=1.5)
    c.line([(10.5, 10.5), (14, 14)], BLUE, 2)
    return c, "resources/elements/test.png"


def refresh_icon():
    c = Canvas()
    c.arc(3, 3, 13, 13, start=40, end=330, fill=GREEN, width=2)
    arrow_head(c, (12.6, 3.4), "up", 2.8, GREEN)
    return c, "components/logviewer/resources/execrefresh_16.png"


def open_icon():
    c = Canvas(20, 16)
    c.polygon([(2, 4), (8, 4), (9.5, 6), (18, 6), (18, 13.5), (2, 13.5)], AMBER)
    c.polygon([(4, 7.5), (19, 7.5), (16.5, 13.5), (2, 13.5)], (0xF2, 0xCC, 0x7E, 255))
    return c, "components/logviewer/resources/open_16.png"


ICONS = [
    run_icon, debug_icon, resume_icon, suspend_icon, terminate_icon,
    step_into_icon, step_over_icon, step_return_icon, breakpoint_icon,
    close_icon, add_icon, delete_icon, replace_icon, save_icon, export_icon,
    grab_icon, test_icon, refresh_icon, open_icon,
]


def main() -> None:
    for factory in ICONS:
        canvas, name = factory()
        canvas.save(name)


if __name__ == "__main__":
    main()
